project:
  type: website
  output-dir: docs

website:
  title: "Quarto Basics"
  navbar:
    background: "#112a39"
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd 


format:
  html:
    title-block-banner: img/landscape.png
    theme: cosmo
    css: styles.css


