project:
  type: website
  output-dir: docs

website:
  title: "ShawnZ's Very Own blog"
  navbar:
    background: "#112a39"
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd 


format:
  html:
    title-block-banner: img/sunset_no_vacancy.jpg
    theme: cosmo
    css: styles.css


